# Generated by Django 5.0.2 on 2024-02-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
